import { Recommendation, StrategyKPI } from './types';

export const strategyKPIs: StrategyKPI[] = [
  { label: 'AI Findability', score: 64, trend: 'up', change: 8 },
  { label: 'Website Health', score: 78, trend: 'stable' },
  { label: 'Brand Authority', score: 52, trend: 'up', change: 12 },
];

export const strategySummary = `As an established B2B SaaS targeting mid-market marketers, your biggest AI visibility gaps are: 1) missing meta structure on key pages, 2) unclear topical authority, 3) thin QFO coverage.`;

export const recommendations: Recommendation[] = [
  // ON-SITE - Quick Wins
  {
    id: 'os-qw-1',
    title: 'Optimize Title Tag',
    plainTitle: 'Clarify your main product in homepage title',
    category: 'on-site',
    subcategory: 'quick-wins',
    businessImpact: 'More qualified demos',
    effort: 'Low',
    whatToChange: 'Your homepage title is generic. Add your primary service and target audience to help AI models understand what you offer.',
    contextNote: 'Based on your B2B SaaS setup, emphasize your analytics platform for marketing teams.',
    whyItMatters: 'AI search engines extract titles to understand page purpose. A clear, specific title increases your chances of appearing in relevant AI responses.',
    technicalDetails: {
      currentTitle: 'Welcome to Our Platform',
      currentH1: 'The Future of Analytics',
    },
    tags: ['On-site', 'AI Snippet'],
    aiVisibilityIncrease: 8,
    contentStudioTemplate: 'title-optimization',
  },
  {
    id: 'os-qw-2',
    title: 'Optimize Meta Description',
    plainTitle: 'Write a compelling product summary for search results',
    category: 'on-site',
    subcategory: 'quick-wins',
    businessImpact: 'Higher click-through',
    effort: 'Low',
    whatToChange: 'Your meta descriptions are missing or auto-generated. Write a 150-character summary that clearly states your value proposition.',
    whyItMatters: 'AI models use meta descriptions as quick summaries. A well-crafted description increases your visibility in AI-generated answers.',
    technicalDetails: {
      currentTitle: '(Auto-generated from page content)',
    },
    tags: ['On-site', 'AI Snippet'],
    aiVisibilityIncrease: 6,
    contentStudioTemplate: 'meta-description',
  },
  {
    id: 'os-qw-3',
    title: 'Optimize H1 Tags',
    plainTitle: 'Make your main heading match what customers search for',
    category: 'on-site',
    subcategory: 'quick-wins',
    businessImpact: 'Better AI matching',
    effort: 'Low',
    whatToChange: 'Your H1 should include your city and primary service since you target local families as a brick & mortar business.',
    contextNote: 'You chose "brick & mortar" and "local families", so add your city and primary service to the homepage H1.',
    whyItMatters: 'H1 tags are primary signals for AI understanding. They should match how your customers describe what they\'re looking for.',
    tags: ['On-site', 'AI Snippet'],
    aiVisibilityIncrease: 7,
    contentStudioTemplate: 'h1-optimization',
  },
  {
    id: 'os-qw-4',
    title: 'Add Alt Text to Key Images',
    plainTitle: 'Describe your product images so AI can understand them',
    category: 'on-site',
    subcategory: 'quick-wins',
    businessImpact: 'Visual search ready',
    effort: 'Low',
    whatToChange: 'Your product images lack descriptive alt text. Add specific descriptions that include product names and key features.',
    whyItMatters: 'AI models increasingly process images. Descriptive alt text helps AI understand and recommend your visual content.',
    tags: ['On-site', 'Accessibility'],
    aiVisibilityIncrease: 4,
    contentStudioTemplate: 'alt-text',
  },

  // ON-SITE - Foundations
  {
    id: 'os-fn-1',
    title: 'Create Topic Clusters',
    plainTitle: 'Build content hubs around your core expertise areas',
    category: 'on-site',
    subcategory: 'foundations',
    businessImpact: 'Establish authority',
    effort: 'Medium',
    whatToChange: 'Group related content into topic clusters with a pillar page linking to detailed sub-pages. Start with your most popular product category.',
    whyItMatters: 'Topic clusters signal expertise to AI models. When your content is well-organized around themes, AI is more likely to cite you as an authority.',
    tags: ['On-site', 'Content Structure'],
    aiVisibilityIncrease: 15,
    contentStudioTemplate: 'topic-cluster',
  },
  {
    id: 'os-fn-2',
    title: 'Add FAQ/QFO Blocks',
    plainTitle: 'Answer the questions your customers actually ask',
    category: 'on-site',
    subcategory: 'foundations',
    businessImpact: 'Capture AI queries',
    effort: 'Medium',
    whatToChange: 'Create FAQ sections for each product page with 10-15 real customer questions. Use natural conversational language.',
    whyItMatters: 'AI assistants love well-structured Q&A content. FAQs are often directly quoted in AI responses to user questions.',
    tags: ['On-site', 'QFO'],
    aiVisibilityIncrease: 18,
    contentStudioTemplate: 'faq-builder',
  },
  {
    id: 'os-fn-3',
    title: 'Implement Schema Markup',
    plainTitle: 'Add structured data so AI models understand your pages',
    category: 'on-site',
    subcategory: 'foundations',
    businessImpact: 'Rich AI results',
    effort: 'Medium',
    whatToChange: 'Add Product, Organization, and FAQ schema to your key pages. This helps AI models parse your content structure.',
    whyItMatters: 'Schema markup is a direct signal to AI models about your content meaning. It significantly increases your chances of rich AI citations.',
    technicalDetails: {
      schema: '{"@context": "https://schema.org", "@type": "Product", ...}',
    },
    tags: ['On-site', 'Technical'],
    aiVisibilityIncrease: 12,
    contentStudioTemplate: 'schema-generator',
  },
  {
    id: 'os-fn-4',
    title: 'Optimize Internal Linking',
    plainTitle: 'Connect your pages so AI can follow your content journey',
    category: 'on-site',
    subcategory: 'foundations',
    businessImpact: 'Better crawling',
    effort: 'Medium',
    whatToChange: 'Add contextual internal links between related content. Use descriptive anchor text that explains what the linked page covers.',
    whyItMatters: 'Internal links help AI crawlers understand your site structure and content relationships, improving overall visibility.',
    tags: ['On-site', 'Structure'],
    aiVisibilityIncrease: 10,
  },

  // ON-SITE - Advanced
  {
    id: 'os-ad-1',
    title: 'Fix Crawlability Issues',
    plainTitle: 'Remove technical barriers that prevent AI from reading your site',
    category: 'on-site',
    subcategory: 'advanced',
    businessImpact: 'Full site indexed',
    effort: 'High',
    whatToChange: 'Fix blocked resources, broken links, and JavaScript rendering issues that prevent AI crawlers from accessing your content.',
    whyItMatters: 'If AI models can\'t crawl your site effectively, they can\'t include you in their knowledge base, regardless of content quality.',
    tags: ['On-site', 'Technical'],
    aiVisibilityIncrease: 20,
  },
  {
    id: 'os-ad-2',
    title: 'Optimize Core Web Vitals',
    plainTitle: 'Make your site fast and responsive for better AI ranking',
    category: 'on-site',
    subcategory: 'advanced',
    businessImpact: 'Improved UX signals',
    effort: 'High',
    whatToChange: 'Improve LCP, FID, and CLS scores. Fast-loading pages with stable layouts are preferred by both users and AI systems.',
    whyItMatters: 'Page experience signals influence how AI models weight your content. Poor performance can reduce your visibility in AI responses.',
    tags: ['On-site', 'Performance'],
    aiVisibilityIncrease: 8,
  },

  // OFF-SITE - Quick Wins
  {
    id: 'of-qw-1',
    title: 'Claim Business Directories',
    plainTitle: 'Get listed in the places AI looks for business info',
    category: 'off-site',
    subcategory: 'quick-wins',
    businessImpact: 'Consistent presence',
    effort: 'Low',
    whatToChange: 'Claim and complete your profiles on Google Business, Bing Places, Apple Maps, and industry-specific directories.',
    whyItMatters: 'AI models cross-reference multiple sources to verify business information. Consistent listings increase your credibility.',
    tags: ['Off-site', 'Directory'],
    aiVisibilityIncrease: 10,
  },
  {
    id: 'of-qw-2',
    title: 'Update Entity Descriptions',
    plainTitle: 'Write a consistent company description for all platforms',
    category: 'off-site',
    subcategory: 'quick-wins',
    businessImpact: 'Clear brand identity',
    effort: 'Low',
    whatToChange: 'Create a standardized 100-word company description and use it consistently across LinkedIn, Crunchbase, and other platforms.',
    whyItMatters: 'Consistent entity descriptions help AI models build a coherent understanding of your brand across the web.',
    tags: ['Off-site', 'Entity'],
    aiVisibilityIncrease: 8,
  },

  // OFF-SITE - Foundations
  {
    id: 'of-fn-1',
    title: 'Build Citation-Worthy Resources',
    plainTitle: 'Create content so valuable that others link to it',
    category: 'off-site',
    subcategory: 'foundations',
    businessImpact: 'Become the source',
    effort: 'High',
    whatToChange: 'Develop original research, comprehensive guides, or industry benchmarks that become reference materials in your space.',
    whyItMatters: 'AI models prioritize content that is widely cited and referenced. Being a primary source dramatically increases your AI visibility.',
    tags: ['Off-site', 'Authority'],
    aiVisibilityIncrease: 25,
    contentStudioTemplate: 'research-guide',
  },
  {
    id: 'of-fn-2',
    title: 'Pursue Strategic Backlinks',
    plainTitle: 'Get mentioned by trusted sites in your industry',
    category: 'off-site',
    subcategory: 'foundations',
    businessImpact: 'Authority signals',
    effort: 'Medium',
    whatToChange: 'Focus on earning links from industry publications, partner sites, and authoritative resources in your niche.',
    whyItMatters: 'Backlinks from trusted sources signal authority to AI models, increasing the weight given to your content.',
    tags: ['Off-site', 'Links'],
    aiVisibilityIncrease: 18,
  },

  // OFF-SITE - Advanced
  {
    id: 'of-ad-1',
    title: 'Strategic Partnerships',
    plainTitle: 'Co-create content with complementary businesses',
    category: 'off-site',
    subcategory: 'advanced',
    businessImpact: 'Expanded reach',
    effort: 'High',
    whatToChange: 'Partner with complementary businesses for co-authored content, joint webinars, or shared research that mentions both brands.',
    whyItMatters: 'Co-citations and partnerships create rich entity connections that AI models use to understand business relationships.',
    tags: ['Off-site', 'Partnership'],
    aiVisibilityIncrease: 15,
  },

  // PR & SOCIAL - Quick Wins
  {
    id: 'pr-qw-1',
    title: 'Collect Customer Reviews',
    plainTitle: 'Ask happy customers to share their experience publicly',
    category: 'pr-social',
    subcategory: 'quick-wins',
    businessImpact: 'Social proof',
    effort: 'Low',
    whatToChange: 'Set up a review request flow and collect reviews on Google, G2, Capterra, or industry-specific platforms.',
    whyItMatters: 'AI models aggregate review sentiment to form brand opinions. Positive reviews across platforms boost your AI reputation.',
    tags: ['PR', 'Reviews'],
    aiVisibilityIncrease: 12,
  },
  {
    id: 'pr-qw-2',
    title: 'Publish Case Studies',
    plainTitle: 'Show real results from real customers',
    category: 'pr-social',
    subcategory: 'quick-wins',
    businessImpact: 'Prove your value',
    effort: 'Medium',
    whatToChange: 'Create 3-5 detailed case studies with specific metrics, customer quotes, and before/after comparisons.',
    whyItMatters: 'Case studies provide concrete evidence that AI models can cite when recommending solutions in your category.',
    tags: ['PR', 'Case Study'],
    aiVisibilityIncrease: 14,
    contentStudioTemplate: 'case-study',
  },

  // PR & SOCIAL - Foundations
  {
    id: 'pr-fn-1',
    title: 'Define Brand Positioning',
    plainTitle: 'Clarify what makes you different from competitors',
    category: 'pr-social',
    subcategory: 'foundations',
    businessImpact: 'Stand out in AI',
    effort: 'Medium',
    whatToChange: 'Document your unique value proposition, key differentiators, and proof points. Use this consistently across all content.',
    contextNote: 'Based on your differentiation input, emphasize your AI-powered analytics and self-service capabilities.',
    whyItMatters: 'Clear positioning helps AI models distinguish you from competitors and recommend you for specific use cases.',
    tags: ['PR', 'Positioning'],
    aiVisibilityIncrease: 16,
    contentStudioTemplate: 'brand-positioning',
  },
  {
    id: 'pr-fn-2',
    title: 'Build Testimonial Library',
    plainTitle: 'Collect and organize customer success stories',
    category: 'pr-social',
    subcategory: 'foundations',
    businessImpact: 'Trusted voice',
    effort: 'Medium',
    whatToChange: 'Gather video and written testimonials. Organize by use case, industry, and customer size for easy reference.',
    whyItMatters: 'Rich testimonial content provides the social proof signals AI models use when evaluating brand credibility.',
    tags: ['PR', 'Testimonials'],
    aiVisibilityIncrease: 10,
  },

  // PR & SOCIAL - Advanced
  {
    id: 'pr-ad-1',
    title: 'Thought Leadership Content',
    plainTitle: 'Position your team as industry experts',
    category: 'pr-social',
    subcategory: 'advanced',
    businessImpact: 'Expert authority',
    effort: 'High',
    whatToChange: 'Publish bylined articles, speak at events, and create original insights that establish your team as go-to experts.',
    whyItMatters: 'Thought leadership creates strong entity associations in AI knowledge bases, improving recommendations.',
    tags: ['PR', 'Thought Leadership'],
    aiVisibilityIncrease: 22,
    contentStudioTemplate: 'thought-leadership',
  },
  {
    id: 'pr-ad-2',
    title: 'Media Outreach Campaign',
    plainTitle: 'Get covered by industry publications',
    category: 'pr-social',
    subcategory: 'advanced',
    businessImpact: 'Press coverage',
    effort: 'High',
    whatToChange: 'Develop a media pitch strategy focusing on your unique insights, product launches, or industry trends.',
    whyItMatters: 'Media mentions from authoritative publications are heavily weighted by AI models when determining expertise.',
    tags: ['PR', 'Media'],
    aiVisibilityIncrease: 20,
  },
];
