import React, { useState } from 'react';
import { 
  Share, 
  Sparkles, 
  ExternalLink,
  ChevronRight,
  Globe,
  Megaphone,
  FileText,
  Calendar as CalendarIcon,
  TrendingUp,
  MoreHorizontal,
  CheckCircle2,
  ArrowRight,
  Trash2,
  AlertTriangle
} from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';

type ActionStatus = 'live' | 'pending' | 'in-progress';
type ActionType = 'on-site' | 'off-site' | 'social' | 'pr';

interface StatusChange {
  from: ActionStatus | null;
  to: ActionStatus;
  date: string;
}

interface ActionItem {
  id: string;
  status: ActionStatus;
  type: ActionType;
  title: string;
  target: string;
  isAiGenerated: boolean;
  author?: string;
  authorAvatar?: string;
  date: string;
  completedDate?: string;
  impactChange?: number;
  campaign?: string;
  description?: string;
  promptUsed?: string;
  history?: { date: string; event: string }[];
  statusHistory?: StatusChange[];
}

const mockActions: ActionItem[] = [
  {
    id: '1',
    status: 'live',
    type: 'pr',
    title: 'TechCrunch Outreach Pitch',
    target: 'techcrunch.com/contact',
    isAiGenerated: true,
    date: '2024-12-21',
    impactChange: 12,
    campaign: 'Q4 Launch',
    description: 'Personalized pitch to TechCrunch editor regarding new AI features launch.',
    promptUsed: 'Generate a pitch email for tech publications highlighting our AI-powered visibility platform.',
    history: [
      { date: '2024-12-21 14:32', event: 'Email sent to editor@techcrunch.com' },
      { date: '2024-12-20 09:15', event: 'Draft generated by Visibl AI' },
      { date: '2024-12-20 08:00', event: 'Action created from Authority Lab' }
    ]
  },
  {
    id: '2',
    status: 'live',
    type: 'on-site',
    title: 'Homepage Meta Description Update',
    target: 'visibl.co/',
    isAiGenerated: true,
    date: '2024-12-20',
    impactChange: 8,
    campaign: 'SEO Optimization',
    description: 'Updated meta description to improve CTR from search results.',
    promptUsed: 'Optimize the homepage meta description for better visibility in AI search results.',
    history: [
      { date: '2024-12-20 16:00', event: 'Changes deployed to production' },
      { date: '2024-12-20 14:30', event: 'Content approved by marketing' },
      { date: '2024-12-20 10:00', event: 'Draft generated by Visibl AI' }
    ]
  },
  {
    id: '3',
    status: 'pending',
    type: 'social',
    title: 'LinkedIn Thought Leadership Post',
    target: 'linkedin.com/company/visibl',
    isAiGenerated: true,
    date: '2024-12-19',
    campaign: 'Brand Awareness',
    description: 'Weekly thought leadership content about AI visibility trends.',
    promptUsed: 'Create a LinkedIn post about the future of brand visibility in the age of AI assistants.'
  },
  {
    id: '4',
    status: 'in-progress',
    type: 'off-site',
    title: 'Guest Article for VentureBeat',
    target: 'venturebeat.com/contributor',
    isAiGenerated: false,
    author: 'Sarah Chen',
    authorAvatar: 'SC',
    date: '2024-12-18',
    campaign: 'PR Outreach',
    description: 'Long-form article about AI visibility metrics for enterprise brands.'
  },
  {
    id: '5',
    status: 'live',
    type: 'on-site',
    title: 'Product Page Schema Markup',
    target: 'visibl.co/product',
    isAiGenerated: true,
    date: '2024-12-17',
    impactChange: 15,
    campaign: 'Technical SEO',
    description: 'Added structured data for better rich snippet display.',
    history: [
      { date: '2024-12-17 11:00', event: 'Schema validated and deployed' },
      { date: '2024-12-17 09:30', event: 'Code review completed' },
      { date: '2024-12-16 16:00', event: 'Implementation started' }
    ]
  },
  {
    id: '6',
    status: 'pending',
    type: 'pr',
    title: 'Podcast Appearance Request',
    target: 'marketingover.coffee',
    isAiGenerated: false,
    author: 'Mike Johnson',
    authorAvatar: 'MJ',
    date: '2024-12-16',
    campaign: 'PR Outreach',
    description: 'Request to appear on Marketing Over Coffee podcast.'
  },
  {
    id: '7',
    status: 'live',
    type: 'social',
    title: 'Twitter/X Thread on LLM Visibility',
    target: 'x.com/visibl',
    isAiGenerated: true,
    date: '2024-12-15',
    impactChange: 6,
    campaign: 'Brand Awareness',
    description: '10-part thread explaining how LLMs choose which brands to cite.'
  },
  {
    id: '8',
    status: 'in-progress',
    type: 'on-site',
    title: 'Blog Post: AI Visibility Guide',
    target: 'visibl.co/blog/ai-visibility-guide',
    isAiGenerated: true,
    date: '2024-12-14',
    campaign: 'Content Marketing',
    description: 'Comprehensive guide on optimizing for AI search engines.',
    promptUsed: 'Write a comprehensive guide about how brands can improve their visibility in AI-powered search results.'
  }
];

const statusConfig: Record<ActionStatus, { label: string; color: string; bgColor: string; glow?: boolean }> = {
  'live': { label: 'Live', color: 'text-emerald-600', bgColor: 'bg-emerald-500', glow: true },
  'pending': { label: 'Pending', color: 'text-amber-600', bgColor: 'bg-amber-500' },
  'in-progress': { label: 'In Progress', color: 'text-blue-600', bgColor: 'bg-blue-500' }
};

const typeConfig: Record<ActionType, { label: string; icon: React.ComponentType<{ className?: string }> }> = {
  'on-site': { label: 'On-site', icon: Globe },
  'off-site': { label: 'Off-site', icon: ExternalLink },
  'social': { label: 'Social', icon: Megaphone },
  'pr': { label: 'PR', icon: FileText }
};

type FilterStatus = 'all' | 'live' | 'pending' | 'in-progress';
type AddStep = 'title' | 'type' | 'target' | 'status';

interface NewAction {
  title: string;
  type: ActionType;
  target: string;
  status: ActionStatus;
}

export function ActionsLog() {
  const [statusFilter, setStatusFilter] = useState<FilterStatus>('all');
  const [selectedAction, setSelectedAction] = useState<ActionItem | null>(null);
  const [actions, setActions] = useState<ActionItem[]>(mockActions);
  
  // Inline add state
  const [isAddingInline, setIsAddingInline] = useState(false);
  const [addStep, setAddStep] = useState<AddStep>('title');
  const [newAction, setNewAction] = useState<NewAction>({
    title: '',
    type: 'on-site',
    target: '',
    status: 'pending'
  });

  const filteredActions = actions.filter(action => {
    if (statusFilter !== 'all' && action.status !== statusFilter) return false;
    return true;
  });

  const liveCount = actions.filter(a => a.status === 'live').length;
  const totalImpact = actions.reduce((sum, a) => sum + (a.impactChange || 0), 0);

  const resetAddForm = () => {
    setIsAddingInline(false);
    setAddStep('title');
    setNewAction({ title: '', type: 'on-site', target: '', status: 'pending' });
  };

  const handleNextStep = () => {
    if (addStep === 'title' && newAction.title.trim()) {
      setAddStep('type');
    } else if (addStep === 'type') {
      setAddStep('target');
    } else if (addStep === 'target') {
      setAddStep('status');
    } else if (addStep === 'status') {
      // Submit the action
      const actionItem: ActionItem = {
        id: Date.now().toString(),
        title: newAction.title.trim(),
        type: newAction.type,
        target: newAction.target.trim() || 'N/A',
        status: newAction.status,
        isAiGenerated: false,
        author: 'You',
        authorAvatar: 'Y',
        date: new Date().toISOString().split('T')[0]
      };
      setActions(prev => [actionItem, ...prev]);
      resetAddForm();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleNextStep();
    }
    if (e.key === 'Escape') {
      resetAddForm();
    }
  };

  const updateActionStatus = (actionId: string, newStatus: ActionStatus, customDate?: Date) => {
    const completedDateValue = customDate ? customDate.toISOString() : new Date().toISOString();
    const nowFormatted = (customDate || new Date()).toLocaleString('en-US', { 
      month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' 
    });

    setActions(prev => prev.map(action => {
      if (action.id !== actionId) return action;
      
      const statusChange: StatusChange = {
        from: action.status,
        to: newStatus,
        date: nowFormatted
      };

      return { 
        ...action, 
        status: newStatus,
        completedDate: newStatus === 'live' ? completedDateValue : action.completedDate,
        statusHistory: [...(action.statusHistory || []), statusChange]
      };
    }));

    // Also update selectedAction if it's the one being changed
    if (selectedAction?.id === actionId) {
      const statusChange: StatusChange = {
        from: selectedAction.status,
        to: newStatus,
        date: nowFormatted
      };
      setSelectedAction(prev => prev ? { 
        ...prev, 
        status: newStatus,
        completedDate: newStatus === 'live' ? completedDateValue : prev.completedDate,
        statusHistory: [...(prev.statusHistory || []), statusChange]
      } : null);
    }
  };


  const deleteAction = (actionId: string) => {
    setActions(prev => prev.filter(action => action.id !== actionId));
    setSelectedAction(null);
  };

  return (
    <div className="flex flex-col h-full bg-background">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-5 border-b border-border/40">
        <div className="flex items-center gap-8">
          <div>
            <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
              Total Actions
            </p>
            <p className="text-2xl font-semibold text-foreground font-mono">
              {mockActions.length}
            </p>
          </div>
          <div className="h-8 w-px bg-border/40" />
          <div>
            <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
              Implemented
            </p>
            <p className="text-2xl font-semibold text-emerald-600 font-mono">
              {liveCount}
            </p>
          </div>
          <div className="h-8 w-px bg-border/40" />
          <div>
            <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
              Impact
            </p>
            <p className="text-2xl font-semibold text-foreground font-mono">
              +{totalImpact}%
            </p>
          </div>
        </div>

        <div className="flex items-center gap-1">
          <button 
            className="p-2 text-muted-foreground hover:text-foreground hover:bg-secondary/60 rounded-md transition-colors"
            title="Share Report"
          >
            <Share className="w-4 h-4" />
          </button>
          <button 
            className="p-2 text-muted-foreground hover:text-foreground hover:bg-secondary/60 rounded-md transition-colors"
            title="More options"
          >
            <MoreHorizontal className="w-4 h-4" />
          </button>
        </div>
      </header>

      {/* Segmented Control */}
      <div className="px-6 py-3 border-b border-border/40">
        <div className="inline-flex bg-secondary/40 rounded-lg p-0.5">
          {(['all', 'live', 'pending', 'in-progress'] as FilterStatus[]).map((status) => (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={`px-3 py-1 text-[12px] font-medium rounded-md transition-all ${
                statusFilter === status
                  ? 'bg-background text-foreground shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              {status === 'all' ? 'All' : status === 'in-progress' ? 'In Progress' : status.charAt(0).toUpperCase() + status.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Actions List */}
      <div className="flex-1 overflow-auto">
        <div className="divide-y divide-border/20">
          {/* Inline Add Row */}
          {isAddingInline ? (
            <div className="px-6 py-3 bg-secondary/20 border-b border-border/30">
              <div className="flex items-center gap-4">
                <div className={`w-2.5 h-2.5 rounded-full ${addStep === 'status' ? statusConfig[newAction.status].bgColor : 'bg-border/50'}`} />
                
                {/* Step indicator */}
                <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground uppercase tracking-wider">
                  <span className={addStep === 'title' ? 'text-foreground font-medium' : ''}>Title</span>
                  <ChevronRight className="w-3 h-3" />
                  <span className={addStep === 'type' ? 'text-foreground font-medium' : ''}>Type</span>
                  <ChevronRight className="w-3 h-3" />
                  <span className={addStep === 'target' ? 'text-foreground font-medium' : ''}>Target</span>
                  <ChevronRight className="w-3 h-3" />
                  <span className={addStep === 'status' ? 'text-foreground font-medium' : ''}>Status</span>
                </div>

                <div className="flex-1" />

                <button
                  onClick={resetAddForm}
                  className="p-1.5 text-muted-foreground hover:bg-secondary rounded transition-colors"
                >
                  <span className="text-[11px] font-medium">esc</span>
                </button>
              </div>

              <div className="mt-3 ml-6">
                {addStep === 'title' && (
                  <input
                    type="text"
                    value={newAction.title}
                    onChange={(e) => setNewAction(prev => ({ ...prev, title: e.target.value }))}
                    placeholder="What did you do? (e.g., Sent pitch to TechCrunch)"
                    className="w-full bg-transparent text-[14px] text-foreground placeholder:text-muted-foreground/50 outline-none"
                    autoFocus
                    onKeyDown={handleKeyDown}
                  />
                )}

                {addStep === 'type' && (
                  <div className="flex items-center gap-2">
                    {(Object.keys(typeConfig) as ActionType[]).map((type) => {
                      const TypeIcon = typeConfig[type].icon;
                      return (
                        <button
                          key={type}
                          onClick={() => {
                            setNewAction(prev => ({ ...prev, type }));
                            setAddStep('target');
                          }}
                          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[12px] font-medium transition-colors ${
                            newAction.type === type
                              ? 'bg-foreground text-background'
                              : 'bg-secondary/60 text-muted-foreground hover:bg-secondary hover:text-foreground'
                          }`}
                        >
                          <TypeIcon className="w-3.5 h-3.5" />
                          {typeConfig[type].label}
                        </button>
                      );
                    })}
                  </div>
                )}

                {addStep === 'target' && (
                  <input
                    type="text"
                    value={newAction.target}
                    onChange={(e) => setNewAction(prev => ({ ...prev, target: e.target.value }))}
                    placeholder="Target URL or destination (optional)"
                    className="w-full bg-transparent text-[14px] text-foreground placeholder:text-muted-foreground/50 outline-none font-mono"
                    autoFocus
                    onKeyDown={handleKeyDown}
                  />
                )}

                {addStep === 'status' && (
                  <div className="flex items-center gap-2">
                    {(Object.keys(statusConfig) as ActionStatus[]).map((status) => (
                      <button
                        key={status}
                        onClick={() => {
                          setNewAction(prev => ({ ...prev, status }));
                          // Auto-submit after status selection
                          const actionItem: ActionItem = {
                            id: Date.now().toString(),
                            title: newAction.title.trim(),
                            type: newAction.type,
                            target: newAction.target.trim() || 'N/A',
                            status: status,
                            isAiGenerated: false,
                            author: 'You',
                            authorAvatar: 'Y',
                            date: new Date().toISOString().split('T')[0]
                          };
                          setActions(prev => [actionItem, ...prev]);
                          resetAddForm();
                        }}
                        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[12px] font-medium transition-colors ${
                          newAction.status === status
                            ? 'bg-foreground text-background'
                            : 'bg-secondary/60 text-muted-foreground hover:bg-secondary hover:text-foreground'
                        }`}
                      >
                        <div className={`w-2 h-2 rounded-full ${statusConfig[status].bgColor}`} />
                        {statusConfig[status].label}
                      </button>
                    ))}
                  </div>
                )}

                {(addStep === 'title' || addStep === 'target') && (
                  <p className="mt-2 text-[11px] text-muted-foreground/60">
                    Press Enter to continue, Esc to cancel
                  </p>
                )}
              </div>
            </div>
          ) : (
            <button
              onClick={() => setIsAddingInline(true)}
              className="w-full px-6 py-3 flex items-center gap-4 text-muted-foreground hover:text-foreground hover:bg-secondary/20 transition-colors text-left"
            >
              <div className="w-2.5 h-2.5 rounded-full border border-dashed border-muted-foreground/40" />
              <span className="text-[13px]">Log an action...</span>
            </button>
          )}

          {/* Action Items */}
          {filteredActions.map((action) => {
            const TypeIcon = typeConfig[action.type].icon;
            const statusStyle = statusConfig[action.status];

            return (
              <button
                key={action.id}
                onClick={() => setSelectedAction(action)}
                className="w-full px-6 py-3.5 flex items-center gap-5 hover:bg-secondary/20 transition-colors text-left group"
              >
                {/* Status Indicator */}
                <div className="flex-shrink-0">
                  <div
                    className={`w-2 h-2 rounded-full ${statusStyle.bgColor} ${
                      statusStyle.glow ? 'shadow-[0_0_6px_1px_rgba(16,185,129,0.5)]' : ''
                    }`}
                  />
                </div>

                {/* Type Badge */}
                <div className="flex-shrink-0">
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-secondary/60 text-muted-foreground text-[10px] font-medium rounded">
                    <TypeIcon className="w-3 h-3" />
                    {typeConfig[action.type].label}
                  </span>
                </div>

                {/* Description */}
                <div className="flex-1 min-w-0">
                  <p className="text-[13px] font-medium text-foreground truncate">
                    {action.title}
                  </p>
                  <p className="text-[11px] text-muted-foreground/70 truncate font-mono">
                    {action.target}
                  </p>
                </div>

                {/* Author */}
                <div className="flex-shrink-0">
                  {action.isAiGenerated ? (
                    <div className="w-5 h-5 rounded-full bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center" title="Visibl AI">
                      <Sparkles className="w-2.5 h-2.5 text-white" />
                    </div>
                  ) : (
                    <div className="w-5 h-5 rounded-full bg-secondary flex items-center justify-center text-[9px] font-medium text-foreground" title={action.author}>
                      {action.authorAvatar}
                    </div>
                  )}
                </div>

                {/* Date & Impact */}
                <div className="flex-shrink-0 w-24 text-right">
                  <p className="text-[11px] text-muted-foreground font-mono">
                    {new Date(action.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                  </p>
                  {action.impactChange && (
                    <p className="text-[11px] font-medium text-emerald-600 font-mono">
                      +{action.impactChange}%
                    </p>
                  )}
                </div>

                {/* Chevron */}
                <ChevronRight className="w-3.5 h-3.5 text-muted-foreground/30 group-hover:text-muted-foreground/60 transition-colors" />
              </button>
            );
          })}
        </div>
      </div>

      {/* Detail Sheet */}
      <Sheet open={!!selectedAction} onOpenChange={() => setSelectedAction(null)}>
        <SheetContent className="w-[440px] sm:w-[480px] overflow-y-auto">
          {selectedAction && (
            <>
              <SheetHeader className="pb-6">
                <div className="flex items-center gap-2 mb-2">
                  <div
                    className={`w-2 h-2 rounded-full ${statusConfig[selectedAction.status].bgColor} ${
                      statusConfig[selectedAction.status].glow ? 'shadow-[0_0_6px_1px_rgba(16,185,129,0.5)]' : ''
                    }`}
                  />
                  <span className={`text-[11px] font-medium ${statusConfig[selectedAction.status].color}`}>
                    {statusConfig[selectedAction.status].label}
                  </span>
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-secondary/60 text-muted-foreground text-[10px] font-medium rounded">
                    {React.createElement(typeConfig[selectedAction.type].icon, { className: "w-3 h-3" })}
                    {typeConfig[selectedAction.type].label}
                  </span>
                </div>
                <SheetTitle className="text-lg font-semibold">{selectedAction.title}</SheetTitle>
                <a 
                  href={`https://${selectedAction.target}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[12px] text-primary hover:underline font-mono flex items-center gap-1"
                >
                  {selectedAction.target}
                  <ExternalLink className="w-3 h-3" />
                </a>
              </SheetHeader>

              <div className="space-y-5">
                {/* Status Selector */}
                <div>
                  <span className="text-[10px] font-medium text-muted-foreground uppercase">Status</span>
                  <div className="mt-2 flex items-center gap-2">
                    {(Object.keys(statusConfig) as ActionStatus[]).map((status) => (
                      <button
                        key={status}
                        onClick={() => updateActionStatus(selectedAction.id, status)}
                        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[12px] font-medium transition-all ${
                          selectedAction.status === status
                            ? 'bg-foreground text-background'
                            : 'bg-secondary/40 text-muted-foreground hover:bg-secondary hover:text-foreground'
                        }`}
                      >
                        <div className={`w-2 h-2 rounded-full ${statusConfig[status].bgColor} ${
                          selectedAction.status === status && statusConfig[status].glow ? 'shadow-[0_0_4px_1px_rgba(16,185,129,0.5)]' : ''
                        }`} />
                        {statusConfig[status].label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Completed Date (shown when status is live) */}
                {selectedAction.status === 'live' && selectedAction.completedDate && (
                  <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-lg">
                    <div className="flex items-center gap-1.5 mb-1">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                      <span className="text-[10px] font-medium text-emerald-600 uppercase">Completed</span>
                    </div>
                    <p className="text-[13px] font-medium font-mono text-emerald-700">
                      {new Date(selectedAction.completedDate).toLocaleDateString('en-US', { 
                        month: 'short', 
                        day: 'numeric',
                        year: 'numeric',
                        hour: 'numeric',
                        minute: '2-digit'
                      })}
                    </p>
                  </div>
                )}

                {/* Meta Info */}
                <div className="grid grid-cols-2 gap-3">
                  <div className="p-3 bg-secondary/20 rounded-lg">
                    <div className="flex items-center gap-1.5 mb-1">
                      <CalendarIcon className="w-3.5 h-3.5 text-muted-foreground" />
                      <span className="text-[10px] font-medium text-muted-foreground uppercase">Created</span>
                    </div>
                    <p className="text-[13px] font-medium font-mono">
                      {new Date(selectedAction.date).toLocaleDateString('en-US', { 
                        month: 'short', 
                        day: 'numeric',
                        year: 'numeric'
                      })}
                    </p>
                  </div>
                  <div className="p-3 bg-secondary/20 rounded-lg">
                    <div className="flex items-center gap-1.5 mb-1">
                      <TrendingUp className="w-3.5 h-3.5 text-muted-foreground" />
                      <span className="text-[10px] font-medium text-muted-foreground uppercase">Impact</span>
                    </div>
                    <p className="text-[13px] font-medium font-mono text-emerald-600">
                      {selectedAction.impactChange ? `+${selectedAction.impactChange}%` : '—'}
                    </p>
                  </div>
                </div>

                {/* Author */}
                <div className="p-3 bg-secondary/20 rounded-lg">
                  <span className="text-[10px] font-medium text-muted-foreground uppercase">Source</span>
                  <div className="mt-2 flex items-center gap-2">
                    {selectedAction.isAiGenerated ? (
                      <>
                        <div className="w-6 h-6 rounded-full bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
                          <Sparkles className="w-3 h-3 text-white" />
                        </div>
                        <span className="text-[13px] font-medium">Visibl AI</span>
                      </>
                    ) : (
                      <>
                        <div className="w-6 h-6 rounded-full bg-secondary flex items-center justify-center text-[10px] font-medium">
                          {selectedAction.authorAvatar}
                        </div>
                        <span className="text-[13px] font-medium">{selectedAction.author}</span>
                      </>
                    )}
                  </div>
                </div>

                {/* Description */}
                {selectedAction.description && (
                  <div>
                    <h4 className="text-[10px] font-medium text-muted-foreground uppercase mb-2">Description</h4>
                    <p className="text-[13px] text-muted-foreground leading-relaxed">
                      {selectedAction.description}
                    </p>
                  </div>
                )}

                {/* AI Prompt */}
                {selectedAction.promptUsed && (
                  <div>
                    <h4 className="text-[10px] font-medium text-muted-foreground uppercase mb-2">AI Prompt Used</h4>
                    <div className="p-3 bg-violet-500/5 border border-violet-500/20 rounded-lg">
                      <p className="text-[12px] text-foreground/80 italic">
                        "{selectedAction.promptUsed}"
                      </p>
                    </div>
                  </div>
                )}

                {/* Status History */}
                {selectedAction.statusHistory && selectedAction.statusHistory.length > 0 && (
                  <div>
                    <h4 className="text-[10px] font-medium text-muted-foreground uppercase mb-3">Status Changes</h4>
                    <div className="space-y-2">
                      {selectedAction.statusHistory.map((change, index) => (
                        <div key={index} className="flex items-center gap-2 text-[12px]">
                          <span className="text-muted-foreground font-mono text-[11px]">{change.date}</span>
                          <span className="text-muted-foreground">—</span>
                          {change.from && (
                            <>
                              <span className={statusConfig[change.from].color}>{statusConfig[change.from].label}</span>
                              <ArrowRight className="w-3 h-3 text-muted-foreground/50" />
                            </>
                          )}
                          <span className={statusConfig[change.to].color}>{statusConfig[change.to].label}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* History */}
                {selectedAction.history && (
                  <div>
                    <h4 className="text-[10px] font-medium text-muted-foreground uppercase mb-3">Activity</h4>
                    <div className="space-y-3">
                      {selectedAction.history.map((item, index) => (
                        <div key={index} className="flex gap-3">
                          <div className="flex flex-col items-center">
                            <div className="w-1.5 h-1.5 rounded-full bg-muted-foreground/40" />
                            {index < selectedAction.history!.length - 1 && (
                              <div className="w-px flex-1 bg-border/40 mt-1" />
                            )}
                          </div>
                          <div className="pb-3">
                            <p className="text-[11px] text-muted-foreground font-mono">{item.date}</p>
                            <p className="text-[12px] text-foreground">{item.event}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Campaign */}
                {selectedAction.campaign && (
                  <div className="pt-3 border-t border-border/30">
                    <span className="text-[10px] font-medium text-muted-foreground uppercase">Campaign</span>
                    <p className="text-[13px] font-medium mt-1">{selectedAction.campaign}</p>
                  </div>
                )}

                {/* Delete Action */}
                <div className="pt-4 mt-4 border-t border-border/30">
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <button
                        className="flex items-center gap-2 px-3 py-2 w-full rounded-md text-[12px] font-medium text-red-600 hover:bg-red-50 dark:hover:bg-red-950/30 transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                        Delete Action
                      </button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle className="flex items-center gap-2">
                          <AlertTriangle className="w-5 h-5 text-red-500" />
                          Delete Action
                        </AlertDialogTitle>
                        <AlertDialogDescription>
                          Are you sure you want to delete "{selectedAction.title}"? This action cannot be undone.
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction
                          onClick={() => deleteAction(selectedAction.id)}
                          className="bg-red-600 hover:bg-red-700 text-white"
                        >
                          Delete
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </div>
            </>
          )}
        </SheetContent>
      </Sheet>
    </div>
  );
}
